### ISSUE TITLE
Unfinished Symphony, or, Partial composition

### ISSUE THREAD

**Issue by som-snytt** [scalapuzzlers/scalapuzzlers.github.com#136]
http://stackoverflow.com/questions/32889413/matcherror-for-partialfunctions-composition-with-orelse

I won't spoil it for you.

```
val testPf1 = PartialFunction[Any, Boolean]{ case 2 ⇒ true }
val testPf2 = PartialFunction[Any, Boolean]{ case 1 ⇒ true }
val testPf = testPf1 orElse testPf2
testPf.isDefinedAt(1)
testPf.isDefinedAt(2)
testPf(1)
testPf(2)
```

I commented on SO that the method in question was added during the overhaul of PartialFunction.applyOrElse, but may be just fodder for puzzlers. IMHO it should have a different name.

**Comment by demobox** [comment]
A very nice one, indeed - so nice, in fact, that it ended up as http://scalapuzzlers.com/#pzzlr-052 when it last came up (#114) ;-)

Thanks for the suggestion!

**Comment by som-snytt** [comment]
Doh! Now I won't get to use the Unfinished Symphony, oh well.

**Comment by demobox** [comment]
> Doh! Now I won't get to use the Unfinished Symphony, oh well.

I'm sure we'll find a use for it somewhere... ;-)
