### ISSUE TITLE
"Top-level" in #21

### ISSUE THREAD

**Issue by som-snytt** [scalapuzzlers/scalapuzzlers.github.com#138]
Following up on https://issues.scala-lang.org/browse/SI-7787, I noticed that the explanatory text of http://scalapuzzlers.com/#pzzlr-021 refers to "top-level" loosely. The spec just says "members of a package are top-level." in 9.2 http://www.scala-lang.org/files/archive/spec/2.11/09-top-level-definitions.html

Not to be all specese. "top-level defs outside a package go in the empty package."

I guess it's just the last line where it gets confusing (respectively, wrong).

>Members of the empty package are however only visible from within the empty package, i.e. only from other top-level classes. In all other packages, top-level objects and classes are not accessible. Real projects will thus never use top-level classes.

**Comment by demobox** [comment]
> I guess it's just the last line where it gets confusing (respectively, wrong).

Any suggestions? Simply remove the line?

**Comment by som-snytt** [comment]
Yes, if it's deleted it can't be wrong. Also s/full qualified identifier/rooted path/ since `base.Y` is "fully-qualified" in the normal (?) sense. Too lazy (busy) to see how spec calls things with _root_.

**Comment by demobox** [comment]
See 48c3b150db8. Thanks, @som-snytt!
