### ISSUE TITLE
Reference to SLS

### ISSUE THREAD

**Issue by dgruntz** [scalapuzzlers/scalapuzzlers.github.com#19]
It would be nice if each puzzle would indicate, in which part of the Scala Language Spec (SLS) the solution of the puzzler behavior is defined. This could also be added to the puzzler template.

Hopefully, the spec will eventually be available online, then links could be added directly. For the time being, reference to the section would be fine.

Dominik

**Comment by demobox** [comment]
Most puzzlers reference some part of the SLS in their explanation - closing for now. Thanks for the suggestion, Dominik!

**Comment by dgruntz** [comment]
It is OK. Thanks for reviewing (and closing) this old comment.
