### ISSUE TITLE
RSS feed for new puzzlers

### ISSUE THREAD

**Issue by demobox** [scalapuzzlers/scalapuzzlers.github.com#24]
See the comment by David Biesack in the following thread on scala-user:

https://groups.google.com/group/scala-user/browse_thread/thread/c531aefe3ba10b39/15e6e67d95e2bbf9?q=scala-user+scala+puzzlers#15e6e67d95e2bbf9

Seems there would be interest in an RSS feed so people could subscribe to new puzzlers...

ap

**Comment by a-wortman** [comment]
I'd also like to see an RSS feed for puzzlers - @demobox or @nermin do either of you have opinions here? I was thinking duct-taping something together on an AWS micro instance should be satisfactory, but that turns into $10/month after the year-long free trial.

**Comment by demobox** [comment]
> do either of you have opinions here?

At present, Nermin is our "RSS feed by proxy" - via the [ScalaPuzzlers Twitter account](https://twitter.com/ScalaPuzzlers) ;-)

**Comment by demobox** [comment]
Closing out old issues - please re-open if you have cycles to potentially look into this!
